blank_issues_enabled: true
contact_links:
  - name: Aixcoin Core Security Policy
    url: https://github.com/aixcoin/aixcoin/blob/master/SECURITY.md
    about: View security policy
  - name: Aixcoin Core Developers
    url: https://aixcoincore.org
    about: Aixcoin Core homepage
